# Enrichment for the 24 "Atomic Knowledge" pages.
# These already have strong, specific Definition & Context text (preserved by
# the runner). Here we supply the missing Why / Best Practices / Common
# Pitfalls / Sources sections, tailored to each topic.

ATOMIC = {}


def _add(slug, why, practices, pitfalls, refs):
    ATOMIC[slug] = {
        "why": why,
        "practices": practices,
        "pitfalls": pitfalls,
        "refs": refs,
    }


_add("action-recorder-autocad",
    "Action Recorder turns repetitive command sequences into replayable macros without any programming, making it the fastest route to automation for drafters who don't write LISP or .NET — ideal for batch cleanup, standard annotation, and block insertion across many drawings.",
    ["Insert request-for-input pauses so a macro can pick new geometry on replay.",
     "Keep macros short and single-purpose; chain them rather than building one giant recording.",
     "Record with absolute vs relative coordinates deliberately depending on reuse.",
     "Store .actm files in a shared support path so the whole team can run them."],
    ["Recording absolute coordinate picks that only work on the original drawing.",
     "No input pauses, so the macro blindly repeats on the wrong geometry.",
     "System-variable state (osnap, layers) differing at playback time.",
     "Over-long recordings that are impossible to debug when one step fails."],
    [("Autodesk — Action Recorder", "https://help.autodesk.com/view/ACD/2024/ENU/?guid=GUID-action-recorder"),
     ("Autodesk — Macros overview", "https://help.autodesk.com/view/ACD/2024/ENU/")])

_add("adaptive-components-revit",
    "Adaptive components let Revit model complex, condition-driven geometry — panelized facades, space frames, parametric railings — that ordinary fixed-insertion families cannot, making them essential for computational and non-standard building geometry.",
    ["Place adaptive points in the logical order the geometry depends on.",
     "Drive adaptive families from a divided surface/pattern for facade panelization.",
     "Keep the family lightweight — heavy adaptive families multiplied across a facade kill performance.",
     "Combine with Dynamo to place and populate adaptive components from data."],
    ["Overly complex adaptive families causing severe model slowdowns.",
     "Placing adaptive points in an order that breaks the flexing logic.",
     "Using adaptive components where a simple parametric family would do.",
     "Ignoring the panel count — thousands of instances can cripple the model."],
    [("Autodesk — Adaptive components", "https://help.autodesk.com/view/RVT/2024/ENU/?guid=GUID-adaptive"),
     ("Autodesk — Dynamo BIM", "https://dynamobim.org/")])

_add("ai-assisted-modeling-bricscad",
    "BricsCAD's AI features (BLOCKIFY, automatic block/parametric recognition) automate the tedious cleanup and rationalization of legacy DWGs, reclaiming file size and editability that would take hours to fix manually — a genuine productivity differentiator among AutoCAD-compatible platforms.",
    ["Run BLOCKIFY on legacy drawings to convert repeated geometry into reusable blocks.",
     "Review AI-proposed changes before accepting; treat suggestions as drafts.",
     "Use parametric/propagate features to replicate patterns intelligently.",
     "Combine AI cleanup with a purge/audit pass for maximum file-size savings."],
    ["Accepting AI groupings blindly without checking edge cases.",
     "Assuming AI recognition is perfect on messy or exploded geometry.",
     "Skipping a backup before large automated modifications.",
     "Expecting identical behaviour to AutoCAD's (different feature set)."],
    [("Bricsys — BricsCAD", "https://www.bricsys.com/"),
     ("Bricsys — BLOCKIFY & AI tools", "https://help.bricsys.com/")])

_add("api-ecosystem-gstarcad",
    "GstarCAD's triple-API stack (GRX, .NET, LISP) lets organisations port existing AutoCAD customization — ARX plug-ins, .NET add-ins, and LISP routines — onto a lower-cost platform, which is the decisive factor for many when migrating away from AutoCAD.",
    ["Assess which APIs your existing tools use before planning a migration.",
     "Port GRX/ARX plug-ins where source is available for near-native performance.",
     "Reuse LISP/DCL routines directly to minimise migration effort.",
     "Target the correct API version matching the GstarCAD release."],
    ["Assuming 100% ARX/.NET compatibility without testing your specific plug-ins.",
     "Ignoring API-version differences between releases.",
     "Porting only code and forgetting DCL dialogs and support files.",
     "No regression testing of migrated tools on real drawings."],
    [("GstarCAD — Developer resources", "https://www.gstarcad.net/"),
     ("Autodesk — ObjectARX", "https://aps.autodesk.com/")])

_add("blenderbim-addon",
    "BlenderBIM (now Bonsai) brings native, standards-compliant IFC authoring to the free Blender platform, giving small practices and open-source advocates a genuine openBIM authoring tool without proprietary licensing — a notable expansion of accessible BIM.",
    ["Author directly to IFC (native IFC workflow) rather than exporting later.",
     "Use IFC schema-valid classes so data exchanges cleanly with other tools.",
     "Leverage Blender's geometry tools while keeping IFC data integrity.",
     "Validate output with an IFC checker before issuing."],
    ["Treating it as a generic mesh tool and losing IFC semantic data.",
     "Producing geometrically valid but schema-invalid IFC.",
     "Expecting full parity with mature commercial BIM authoring tools.",
     "Skipping IFC validation before handover."],
    [("Bonsai (BlenderBIM)", "https://bonsaibim.org/"),
     ("buildingSMART — IFC", "https://www.buildingsmart.org/")])

_add("collaborative-design-gstarcad",
    "GstarCAD's collaboration features (cloud storage, references, and shared workflows) let distributed teams work on shared drawings with controlled references, addressing the multi-user coordination that plain file sharing handles poorly.",
    ["Use external references (Xrefs) to partition work between team members.",
     "Establish a shared, backed-up storage location with clear file ownership.",
     "Agree layer/naming standards so merged work stays consistent.",
     "Coordinate Xref reload/notification so everyone sees current data."],
    ["Editing shared files with no locking, causing overwrites.",
     "Broken Xref paths from moving files without repathing.",
     "Inconsistent standards making merged drawings messy.",
     "No backup discipline on the shared location."],
    [("GstarCAD", "https://www.gstarcad.net/"),
     ("Autodesk — Xref best practices", "https://help.autodesk.com/view/ACD/2024/ENU/")])

_add("data-link-autocad",
    "Data links connect AutoCAD tables to live Excel spreadsheets, so schedules, BOMs, and quantity data update automatically when the source changes — eliminating error-prone manual re-typing between drawing and spreadsheet.",
    ["Link to a defined named range so the table maps predictably.",
     "Set the update direction deliberately (Excel→table is the common case).",
     "Keep the linked workbook in a stable, shared path to avoid broken links.",
     "Use cell formatting/formulas in Excel and let AutoCAD reflect them."],
    ["Moving/renaming the source workbook and breaking the link.",
     "Editing the AutoCAD table directly, causing conflicts on update.",
     "Linking whole sheets instead of tidy named ranges.",
     "Forgetting to update the link before plotting."],
    [("Autodesk — Data links", "https://help.autodesk.com/view/ACD/2024/ENU/?guid=GUID-datalink"),
     ("Autodesk — Tables", "https://help.autodesk.com/view/ACD/2024/ENU/")])

_add("design-options-revit",
    "Design Options let a Revit model hold several design alternatives (e.g. two lobby layouts) in one file, so teams can develop, compare, and present variants without duplicating the whole model — essential for early-stage optioneering.",
    ["Keep only genuinely varying elements in options; shared elements stay in the main model.",
     "Name option sets and options clearly for the team.",
     "Use view-specific option visibility to present each scheme.",
     "Accept the chosen option cleanly to fold it back into the model."],
    ["Putting too many elements into options, complicating the model.",
     "Editing main-model elements while an option is active by mistake.",
     "Confusion over which option a view is displaying.",
     "Never resolving options, leaving a cluttered model."],
    [("Autodesk — Design Options", "https://help.autodesk.com/view/RVT/2024/ENU/?guid=GUID-design-options"),
     ("Autodesk Revit help", "https://help.autodesk.com/view/RVT/2024/ENU/")])

_add("electronics-fusion",
    "Fusion's integrated electronics (from EAGLE) unify schematic capture, PCB layout, and the mechanical model in one product, giving true ECAD-MCAD co-design — the board and its enclosure stay synchronized, catching fit issues early.",
    ["Keep schematic and PCB in sync using the push/back-annotate workflow.",
     "Use the live ECAD-MCAD link to check board fit within the enclosure.",
     "Manage libraries/parts consistently for reliable footprints.",
     "Run DRC (design rule checks) before manufacturing output."],
    ["Layout changes not back-annotated to the schematic.",
     "Component heights/connectors colliding with the enclosure.",
     "Wrong or unverified footprints causing fabrication errors.",
     "Skipping DRC before generating Gerbers."],
    [("Autodesk — Fusion electronics", "https://www.autodesk.com/products/fusion-360/"),
     ("Autodesk — EAGLE", "https://www.autodesk.com/products/eagle/")])

_add("express-tools-autocad",
    "Express Tools bundle dozens of productivity commands (text, layers, blocks, dimensions) that automate common drafting chores AutoCAD's core lacks — small individually but a large cumulative time-saver for daily drafting.",
    ["Learn the high-value tools (TEXTFIT, BURST, LAYISO, ALIGNSPACE) you use daily.",
     "Verify Express Tools is installed/loaded — it's an optional component.",
     "Use BURST to explode blocks while retaining attribute values as text.",
     "Combine with core commands in scripts/macros for bigger automations."],
    ["Assuming Express Tools is always installed (it can be omitted).",
     "Relying on tools not available in AutoCAD LT.",
     "Using EXPLODE where BURST would preserve attributes.",
     "Not realising some tools are unsupported/legacy."],
    [("Autodesk — Express Tools", "https://help.autodesk.com/view/ACD/2024/ENU/?guid=GUID-express-tools"),
     ("Autodesk AutoCAD help", "https://help.autodesk.com/view/ACD/2024/ENU/")])

_add("featurescript-onshape",
    "FeatureScript is Onshape's open, typed programming language for authoring custom parametric features — the same language Onshape's own features are built in — enabling teams to encode bespoke geometry operations that behave like native tools.",
    ["Use the FeatureScript Standard Library and study built-in features as examples.",
     "Type inputs precisely and validate them for robust custom features.",
     "Develop in the Feature Studio with the built-in debugger/print.",
     "Version and share custom features so the team reuses them."],
    ["Poorly validated inputs causing custom features to fail on edit.",
     "Reinventing geometry the Standard Library already provides.",
     "Not versioning custom features, breaking documents on updates.",
     "Ignoring performance in geometry-heavy custom features."],
    [("Onshape — FeatureScript", "https://cad.onshape.com/FsDoc/"),
     ("Onshape — Learning center", "https://www.onshape.com/en/resource-center")])

_add("geometry-nodes-blender",
    "Geometry Nodes give Blender a non-destructive, procedural modelling system — building geometry from a node graph driven by parameters — enabling scatter systems, parametric assets, and data-driven models reusable across projects.",
    ["Build reusable node groups with clean exposed parameters.",
     "Work non-destructively; keep the base mesh editable.",
     "Use instancing for scatter/arrays instead of real geometry for performance.",
     "Name sockets and organise the graph for maintainability."],
    ["Sprawling, undocumented node graphs no one can maintain.",
     "Realising instances unnecessarily, tanking performance.",
     "Hard-coding values that should be exposed parameters.",
     "Ignoring attribute domains, causing unexpected results."],
    [("Blender — Geometry Nodes", "https://docs.blender.org/manual/en/latest/modeling/geometry_nodes/"),
     ("Blender manual", "https://docs.blender.org/manual/en/latest/")])

_add("ifc-standard",
    "IFC (Industry Foundation Classes) is the ISO 16739 open, vendor-neutral data model that lets BIM tools exchange building information, making it the cornerstone of openBIM and a requirement in many national BIM mandates.",
    ["Agree the IFC version (IFC4/IFC2x3) and Model View Definition (MVD) for exchange.",
     "Map elements to correct IFC classes and property sets before export.",
     "Validate exports with an IFC checker (e.g. Solibri, IfcOpenShell) and IDS.",
     "Use IFC for coordination/handover, keeping native files for authoring."],
    ["Exporting to the wrong IFC version/MVD for the recipient.",
     "Mis-classified elements (walls exported as generic proxies).",
     "Assuming round-trip IFC editing is lossless.",
     "Skipping validation, so bad data reaches partners."],
    [("buildingSMART — IFC", "https://www.buildingsmart.org/standards/bsi-standards/industry-foundation-classes/"),
     ("ISO 16739", "https://www.iso.org/standard/70303.html")])

_add("mep-systems-revit",
    "Revit MEP models mechanical, electrical, and plumbing systems as connected, analysable networks — not just geometry — so airflow, loads, pressure drop, and circuiting can be calculated and coordinated within the building model.",
    ["Build proper connected systems so flow/load analysis works.",
     "Coordinate MEP with structure/architecture using clash detection.",
     "Use system-based colour/filters to check connectivity and zoning.",
     "Detail to fabrication LOD where prefabrication is planned."],
    ["Drawing MEP as disconnected geometry, breaking system analysis.",
     "Ignoring above-ceiling coordination and floor-to-floor limits.",
     "Incorrect system classification skewing calculations.",
     "Design-LOD content used directly for fabrication."],
    [("Autodesk — Revit MEP", "https://help.autodesk.com/view/RVT/2024/ENU/?guid=GUID-mep"),
     ("ASHRAE", "https://www.ashrae.org/")])

_add("mesh-modeling-fusion",
    "Fusion's mesh workspace handles triangle-mesh data — imported scans and STLs — letting engineers repair, reduce, and convert meshes to BRep or design around them, bridging reality capture and parametric CAD.",
    ["Repair (fill holes, fix normals) before converting or referencing a mesh.",
     "Reduce/remesh heavy scans to workable density.",
     "Convert prismatic scans to parametric BRep; keep organic ones as mesh.",
     "Use mesh as a canvas to model new parametric geometry against."],
    ["Converting huge, unrepaired meshes and crashing/bloating the model.",
     "Auto-converting organic meshes to BRep unnecessarily.",
     "Ignoring flipped normals/holes before downstream use.",
     "Expecting scan meshes to be tolerance-accurate CAD."],
    [("Autodesk — Fusion mesh", "https://help.autodesk.com/view/fusion360/ENU/?guid=MESH"),
     ("Autodesk Fusion", "https://www.autodesk.com/products/fusion-360/")])

_add("purge-audit-recover-autocad",
    "PURGE, AUDIT, and RECOVER are AutoCAD's file-hygiene commands: PURGE removes unused named objects to shrink files, AUDIT fixes internal errors in an open drawing, and RECOVER opens and repairs corrupt DWGs — essential first aid for bloated or damaged files.",
    ["Run PURGE (including zero-length geometry and empty regapps) to cut file size.",
     "AUDIT and fix errors periodically on working drawings.",
     "Use RECOVER on files that won't open normally.",
     "Keep backups before aggressive purging of a shared file."],
    ["Assuming a single PURGE pass removes everything (run it repeatedly).",
     "Ignoring persistent AUDIT errors that signal deeper corruption.",
     "Editing a corrupt file instead of RECOVERing it first.",
     "Purging shared drawings without a backup."],
    [("Autodesk — Purge/Audit/Recover", "https://help.autodesk.com/view/ACD/2024/ENU/?guid=GUID-recover"),
     ("Autodesk — Repair corrupted drawings", "https://www.autodesk.com/support/technical/")])

_add("quantity-takeoff-civil-3d",
    "Civil 3D quantity takeoff derives material volumes and pay-item quantities directly from the design model (corridors, surfaces, pipe networks), keeping quantities live as the design changes — far more reliable than manual measurement for earthwork and construction estimating.",
    ["Define pay item lists and formulae mapped to model objects.",
     "Compute earthwork from accurate existing/proposed surfaces.",
     "Use material sections/corridors for quantity extraction by station.",
     "Re-run takeoff as the design evolves for live quantities."],
    ["Quantities from inaccurate surfaces or incomplete corridors.",
     "Ignoring shrink/swell factors in earthwork.",
     "Manual measurement where model-based takeoff is available.",
     "Not reconciling model quantities against pay-item definitions."],
    [("Autodesk — Civil 3D quantity takeoff", "https://help.autodesk.com/view/CIV3D/2024/ENU/?guid=GUID-qto"),
     ("Autodesk Civil 3D", "https://www.autodesk.com/products/civil-3d/")])

_add("routing-solidworks",
    "SOLIDWORKS Routing automates the design of pipes, tubes, and electrical cables/harnesses within assemblies, generating route geometry, fittings, and manufacturing data (BOMs, flattened harnesses) instead of modelling each segment by hand.",
    ["Use route templates and a curated fitting/component library.",
     "Let auto-route generate paths, then refine bend radii and clips.",
     "Generate flattened harness drawings and accurate wire/pipe lengths.",
     "Keep the Routing add-in and library consistent across the team."],
    ["Modelling routes manually instead of using the Routing tools.",
     "Ignoring bend-radius limits, producing unmanufacturable routes.",
     "Incomplete fitting libraries causing broken routes.",
     "Lengths that ignore slack/service loops."],
    [("SOLIDWORKS — Routing", "https://help.solidworks.com/"),
     ("Dassault SOLIDWORKS", "https://www.solidworks.com/")])

_add("simulation-fusion",
    "Fusion Simulation brings integrated FEA (static stress, modal, thermal, buckling) and generative studies into the same environment as the CAD model, letting designers validate parts against loads without exporting to a separate solver.",
    ["Simplify geometry (remove tiny fillets/holes) before meshing where valid.",
     "Apply realistic constraints and loads; check reactions balance.",
     "Refine the mesh (convergence) at high-stress regions.",
     "Interpret singularities at sharp corners with caution."],
    ["Trusting a single coarse mesh with no convergence check.",
     "Over-constraining, hiding real deflection.",
     "Reading peak stress at geometric singularities as real.",
     "Wrong material/units producing meaningless results."],
    [("Autodesk — Fusion simulation", "https://help.autodesk.com/view/fusion360/ENU/?guid=SIM"),
     ("Autodesk Fusion", "https://www.autodesk.com/products/fusion-360/")])

_add("step-file-format",
    "STEP (ISO 10303) is the dominant neutral CAD exchange format for solid/BRep geometry between MCAD systems; the modern AP242 protocol also carries PMI/MBD data, making it the backbone of multi-tool mechanical interoperability.",
    ["Use AP242 when you need PMI/MBD; AP203/AP214 for geometry only.",
     "Export solids (not surfaces) where downstream tools need solids.",
     "Validate the imported model (geometry checks, healing) after translation.",
     "Agree the STEP AP and version with partners before exchange."],
    ["Using AP203 when PMI/MBD data was required (needs AP242).",
     "Assuming STEP round-trips features — it transfers dumb solids.",
     "Skipping validation/healing of imported geometry.",
     "Exporting surfaces where solids were expected."],
    [("STEP AP242", "https://www.ap242.org/"),
     ("ISO 10303", "https://www.iso.org/standard/63141.html")])

_add("surfacing-techniques-solidworks",
    "SOLIDWORKS surfacing tools (boundary, loft, fill, sweep, and continuity control) build complex freeform and hybrid solid-surface geometry that prismatic feature modelling can't, essential for consumer products, ergonomic forms, and Class-A styling.",
    ["Control curvature continuity (tangent/curvature) for smooth, fair surfaces.",
     "Check quality with zebra stripes and curvature combs.",
     "Build clean, minimal boundary curves before lofting/blending.",
     "Knit surfaces into a watertight body before thickening/solidifying."],
    ["Tangent-only continuity where reflections demand curvature (G2).",
     "Messy input curves producing lumpy, un-fair surfaces.",
     "Failed knits/thicken from gaps or overlaps.",
     "Over-trimmed surface soup that breaks downstream operations."],
    [("SOLIDWORKS — Surfacing", "https://help.solidworks.com/"),
     ("Dassault SOLIDWORKS", "https://www.solidworks.com/")])

_add("survey-database-civil-3d",
    "The Civil 3D survey database stores field survey data — points, figures, and setups — with survey-specific tools (traverse, adjustment, figure prefixes) that build surfaces and linework directly from surveyor observations, keeping survey data managed and auditable.",
    ["Use figure prefix libraries so field codes build linework automatically.",
     "Perform traverse analysis/adjustment before building surfaces.",
     "Keep the survey database as the managed source of raw field data.",
     "Verify point/figure coding against the field book."],
    ["Importing raw points with no coding, losing automatic linework.",
     "Skipping traverse adjustment, propagating field error.",
     "Editing derived data instead of the survey source.",
     "Coordinate/datum mismatches with the project."],
    [("Autodesk — Civil 3D survey", "https://help.autodesk.com/view/CIV3D/2024/ENU/?guid=GUID-survey"),
     ("Autodesk Civil 3D", "https://www.autodesk.com/products/civil-3d/")])

_add("view-templates-revit",
    "View templates in Revit apply a consistent set of view properties — visibility/graphics, detail level, scale, filters — to many views at once, enforcing graphic standards and saving enormous manual setup across a large sheet set.",
    ["Create templates per view type (plan, section, elevation) and assign them.",
     "Control visibility/graphics and filters through templates, not per view.",
     "Assign templates to views so overrides stay centrally managed.",
     "Store templates in the project template for reuse across projects."],
    ["Manually setting graphics on each view instead of using templates.",
     "Inconsistent view standards from ad-hoc overrides.",
     "Templates that lock too many properties, frustrating users.",
     "Not carrying templates into the office project template."],
    [("Autodesk — View templates", "https://help.autodesk.com/view/RVT/2024/ENU/?guid=GUID-view-templates"),
     ("Autodesk Revit help", "https://help.autodesk.com/view/RVT/2024/ENU/")])

_add("viewport-configuration-autocad",
    "Viewport configuration is what lets a single AutoCAD model produce a professional multi-view sheet set — plan, elevation, and detail at different scales on one layout — with per-viewport layer control, so drawings stay coordinated to the model without duplicating geometry.",
    ["Lock viewport scale immediately after setting it to prevent accidental zoom.",
     "Use annotative objects so text/dimensions scale correctly per viewport.",
     "Control per-viewport layer visibility with VP Freeze.",
     "For large sheet sets, drive viewports from named views via Sheet Set Manager."],
    ["Unlocked viewports whose scale changes on an accidental zoom.",
     "Non-annotative text that's the wrong size in different-scale viewports.",
     "Manually managing 50+ sheets instead of using Sheet Set Manager.",
     "Overlapping/mis-clipped viewports cluttering the layout."],
    [("Autodesk — Layout viewports", "https://help.autodesk.com/view/ACD/2024/ENU/?guid=GUID-viewports"),
     ("Autodesk — Sheet Set Manager", "https://help.autodesk.com/view/ACD/2024/ENU/")])
